# SPDX-FileCopyrightText: 2026 ETH Zurich, University of Bologna and EssilorLuxottica SAS
#
# SPDX-License-Identifier: Apache-2.0

include $(PULPOS_HOME)/rules/pulpos_config.mk

APP       = hello
APP_SRCS += test.c

include $(PULPOS_HOME)/rules/pulpos.mk
