// SPDX-FileCopyrightText: 2026 ETH Zurich, University of Bologna and EssilorLuxottica SAS
//
// SPDX-License-Identifier: Apache-2.0
//
// Authors: Germain Haugou (germain.haugou@gmail.com)

#include <stdlib.h>
#include <stdint.h>
#include <kernel/init.h>
#ifdef CONFIG_IRQ
#include <pmsis/kernel/irq.h>
#endif
#ifdef CONFIG_THREAD
#include <pmsis/kernel/thread.h>
#endif
#include <kernel/link.h>
#include <kernel/hal.h>
#include <lib/libc/minimal/libc.h>


// Function type for constructors / desctructors
typedef void (*__ctor_dtor_ptr_t)(void);

// COnstructors generated by the compiler. They are stored in a dedicated section
static __ctor_dtor_ptr_t ctor_list[1] __attribute__((section(".ctors.start"))) =
    { (__ctor_dtor_ptr_t) - 1 };

// Destructors generated by the compiler. They are stored in a dedicated section
static __ctor_dtor_ptr_t dtor_list[1] __attribute__((section(".dtors.start"))) =
    { (__ctor_dtor_ptr_t) - 1 };

// External main function brought by user code and called by our init function
extern int main();


// Call all constructors one by one
static void __pi_init_do_ctors(void)
{
    __ctor_dtor_ptr_t *fpp;

    for(fpp = ctor_list+1;  *fpp != 0;  ++fpp)
    {
        (**fpp)();
    }
}


// Call all destructors one by one
static void __pi_init_do_dtors(void)
{
    __ctor_dtor_ptr_t *fpp;
    for(fpp = dtor_list + 1;  *fpp != 0;  ++fpp)
    {
        (**fpp)();
    }
}



static __attribute__((noinline)) void __pi_init_bss()
{
    unsigned int *bss = (unsigned int *)__pi_init_bss_start();
    unsigned int *bss_end = (unsigned int *)__pi_init_bss_end();

    // INIT_INF("BSS init (start: 0x%x, end: 0x%x)\n", bss, bss_end);

    while (bss != bss_end)
    {
        *bss++ = 0;
    }
}



void __pi_init_start()
{
    // BSS init
    __pi_init_bss();

#ifdef CONFIG_LIBC
    // Early libc initialization to have printf ready as soon as possible.
    // This will make it available only for simple devices like semi-hosting, not for uart.
    __pi_libc_init();
#endif

#ifdef CONFIG_EVENT
    __pi_evt_sched_init();
#endif

#ifdef CONFIG_IRQ
    __pi_irq_init();
#endif

#ifdef CONFIG_THREAD
    __pi_thread_sched_init();
#endif

    // Call global and static constructors
    // Each module may do private initializations there
    __pi_init_do_ctors();

    // Soc specific initializations
    __pi_init_soc();

#ifdef CONFIG_LIBC
    // Now that the system is ready, activate more complex IO like uart
    __pi_libc_start();
#endif

#ifdef CONFIG_IRQ
    // Now now the minimal init are done, we can activate interruptions
    __pi_irq_global_enable();
#endif

    int retval = main();

    // Propagate retval to the loader
    __pi_init_stop(retval);

    return;

error:
    __pi_init_stop(-1);
}



void __pi_init_stop(int status)
{
#ifdef CONFIG_LIBC
    // Close IO to flush them
    __pi_libc_stop();
#endif

    // Call global and static destructors
    __pi_init_do_dtors();

    // Stop the platform
    __pi_init_platform_exit(status);
}
