# SPDX-License-Identifier: Apache-2.0
#
# PulpOS make flow — generic application rules.
#
# Usage (application Makefile):
#
#     include $(PULPOS_HOME)/rules/pulpos_config.mk   # optional: HW facts
#     APP       = hello
#     APP_SRCS += hello.c
#     APP_CFLAGS += -O2
#     CONFIG_GAP9_BUILD_OS_OPT_LEVEL := 2             # per-app OS config
#     include $(PULPOS_HOME)/rules/pulpos.mk          # must come LAST
#
# The application (and PulpOS itself) build into ./build by default
# (override with 'build=<dir>').  Select the target with 'make target=<name>'
# or the PULPOS_TARGET variable, and the platform with 'make platform=<p>'
# or PULPOS_PLATFORM (an SDK's sourceme.sh can export defaults for both so a
# plain 'make run' works; the command line always overrides).  The included
# rules are generated by bforge at SDK build time for each built target, so
# they always match the current target description.  'make gui=1 run' opens
# the simulation in the GVSoC GUI; run_options=<opts> passes extra gvrun
# options.

_PULPOS_RULES_DIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(_PULPOS_RULES_DIR)pulpos_target.mk
include $(BFORGE_PROPERTIES)

# Platform selection mirrors the target: 'make platform=<p>' (what gvtest
# passes) wins, then the PULPOS_PLATFORM variable (command line or
# environment), else the generated default (gvsoc).  The OS is built for it
# too: the platform is a field of the OS configuration (pulpos_sw), under the
# make prefix the OS build description exports as HW_OS_CONFIG_PREFIX.
PULPOS_PLATFORM := $(or $(platform),$(PULPOS_PLATFORM))
ifneq ($(PULPOS_PLATFORM),)
ifneq ($(HW_OS_CONFIG_PREFIX),)
$(HW_OS_CONFIG_PREFIX)_PULPOS_SW_PLATFORM := $(PULPOS_PLATFORM)
endif
endif

# Application name → build target (bin/<APP>.elf).
APP ?= app
APP_BUILD_TARGET := $(APP)

# gvtest passes the build dir as 'build=<dir>'; must be mapped before os_top —
# the generated module fragments expand $(BUILD_DIR) immediately.  The default
# is set here (not just in os_top) so user variables referencing $(BUILD_DIR)
# expand correctly when snapshot below.
ifneq ($(build),)
BUILD_DIR := $(build)
endif
BUILD_DIR ?= build

# os_top seeds APP_CFLAGS/APP_DEFINES/APP_INCLUDES/APP_LDFLAGS with ':=',
# which would clobber values set above; snapshot and re-append after.
_PULPOS_USER_APP_CFLAGS := $(APP_CFLAGS)
_PULPOS_USER_APP_DEFINES := $(APP_DEFINES)
_PULPOS_USER_APP_INCLUDES := $(APP_INCLUDES)
_PULPOS_USER_APP_LDFLAGS := $(APP_LDFLAGS)
APP_CFLAGS :=
APP_DEFINES :=
APP_INCLUDES :=
APP_LDFLAGS :=

include $(BFORGE_OS_TOP)

APP_CFLAGS += $(_PULPOS_USER_APP_CFLAGS)
APP_DEFINES += $(_PULPOS_USER_APP_DEFINES)
APP_INCLUDES += $(_PULPOS_USER_APP_INCLUDES)
APP_LDFLAGS += $(_PULPOS_USER_APP_LDFLAGS)

# Link the OS objects and depend on generated link inputs (linker script).
APP_LIBS += $(OS_LIBS)
APP_LINK_DEPS += $(OS_LINK_DEPS)

# Run configuration: ':=' here wins over the '?=' defaults in os_bottom.
ifneq ($(PULPOS_PLATFORM),)
PMSIS_RUN_PLATFORM := $(PULPOS_PLATFORM)
endif
PMSIS_RUN_TARGET_NAME := $(PULPOS_TARGET)
PMSIS_RUN_MODEL_DIRS := $(PULPOS_INSTALL_DIR)/models
PMSIS_RUN_TARGET_DIRS := $(PULPOS_INSTALL_DIR)/targets $(PULPOS_INSTALL_DIR)/generators
# gvrun runs in the build directory so its run artifacts (flash image,
# gvsoc config, runtime config, traces) do not land in the application
# sources; the binary must then be absolute since gvrun chdirs there.
PMSIS_RUN_EXE := $(abspath $(BUILD_DIR))/bin/$(APP_BUILD_TARGET).elf
# The binary comes from --parameter chip/binary=...; never let gvrun pick up
# a legacy config.py from the application directory.  Applications add their
# own gvrun options with APP_RUN_OPTIONS (in the Makefile) or run_options=
# (on the make command line); 'make gui=1 run' opens the simulation in the
# GVSoC GUI.
PMSIS_RUN_OPTIONS += --work-dir $(abspath $(BUILD_DIR)) --no-config-py
ifeq ($(gui),1)
PMSIS_RUN_OPTIONS += --gui
endif
PMSIS_RUN_OPTIONS += $(APP_RUN_OPTIONS) $(run_options)

.DEFAULT_GOAL := $(APP_BUILD_TARGET)
.PHONY: all build
all build: $(APP_BUILD_TARGET)

include $(BFORGE_OS_BOTTOM)
